name: Deploy master branch

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    environment: production
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i && npm run build
      - name: Install Plugin and Deploy
        uses: serverless/github-action@v3.1
        with:
          args: -c "serverless plugin install --name serverless-plugin-optimize && serverless plugin install --name serverless-offline && serverless plugin install --name serverless-dynamodb-local && serverless deploy --stage production"
          entrypoint: /bin/sh
        env:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}